export const Brand = {
  name: "entrox",
  product: "Entrox",
  command: "entrox",
  display: "entrox CLI",
  short: "EX",
  packageName: "entrox",
  npmPackageName: "entrox",
  appDirectory: "entrox",
  configBase: "entrox",
  projectDirectory: ".entrox",
  databaseBase: "entrox",
  mdnsDefault: "entrox.local",
  userAgentProduct: "entrox",
  defaultSoundPack: "entrox.default",
  legacyCommand: "opencode",
  legacyPackageName: "opencode",
  legacyNpmPackageName: "opencode-ai",
  legacyAppDirectory: "opencode",
  legacyConfigBase: "opencode",
  legacyProjectDirectory: ".opencode",
  legacyDatabaseBase: "opencode",
  legacyMdnsDefault: "opencode.local",
  legacyDefaultSoundPack: "opencode.default",
} as const
