export const Brand = {
  name: "entrox",
  product: "Entrox",
  command: "entrox",
  display: "entrox CLI",
  short: "EX",
  configBase: "entrox",
  projectDirectory: ".entrox",
  defaultSoundPack: "entrox.default",
  authProviderURL: "https://entrox.996icu.wiki",
  showConfiguredProvidersInConnectDialog: false,
  visibleModelProviderIDs: ["entrox"],
  visibleModelProviderIDPrefixes: ["entrox-"],
  websiteURL: "https://entrox.996icu.wiki",
  docsURL: "https://entrox.996icu.wiki/docs",
  issueURL: "https://entrox.996icu.wiki/support",
  wellKnownPath: "/.well-known/opencode",
  legacyCommand: "opencode",
  legacyConfigBase: "opencode",
  legacyProjectDirectory: ".opencode",
  legacyDefaultSoundPack: "opencode.default",
} as const
